// Generated by npm run generate:registry. Do not edit by hand.
import apatosaurusPreviewDesktopStandard from '@/src/content/animals/apatosaurus/images/preview-desktop-standard.webp'
import apatosaurusPreviewDesktopWide from '@/src/content/animals/apatosaurus/images/preview-desktop-wide.webp'
import apatosaurusPreviewLandscapeCompact from '@/src/content/animals/apatosaurus/images/preview-landscape-compact.webp'
import apatosaurusPreviewPhoneCompact from '@/src/content/animals/apatosaurus/images/preview-phone-compact.webp'
import apatosaurusPreviewPhoneTall from '@/src/content/animals/apatosaurus/images/preview-phone-tall.webp'
import apatosaurusPreviewTabletPortrait from '@/src/content/animals/apatosaurus/images/preview-tablet-portrait.webp'
import dilophosaurusPreviewDesktopStandard from '@/src/content/animals/dilophosaurus/images/preview-desktop-standard.webp'
import dilophosaurusPreviewDesktopWide from '@/src/content/animals/dilophosaurus/images/preview-desktop-wide.webp'
import dilophosaurusPreviewLandscapeCompact from '@/src/content/animals/dilophosaurus/images/preview-landscape-compact.webp'
import dilophosaurusPreviewPhoneCompact from '@/src/content/animals/dilophosaurus/images/preview-phone-compact.webp'
import dilophosaurusPreviewPhoneTall from '@/src/content/animals/dilophosaurus/images/preview-phone-tall.webp'
import dilophosaurusPreviewTabletPortrait from '@/src/content/animals/dilophosaurus/images/preview-tablet-portrait.webp'
import gigantoraptorPreviewDesktopStandard from '@/src/content/animals/gigantoraptor/images/preview-desktop-standard.webp'
import gigantoraptorPreviewDesktopWide from '@/src/content/animals/gigantoraptor/images/preview-desktop-wide.webp'
import gigantoraptorPreviewLandscapeCompact from '@/src/content/animals/gigantoraptor/images/preview-landscape-compact.webp'
import gigantoraptorPreviewPhoneCompact from '@/src/content/animals/gigantoraptor/images/preview-phone-compact.webp'
import gigantoraptorPreviewPhoneTall from '@/src/content/animals/gigantoraptor/images/preview-phone-tall.webp'
import gigantoraptorPreviewTabletPortrait from '@/src/content/animals/gigantoraptor/images/preview-tablet-portrait.webp'
import ichthyosaurPreviewDesktopStandard from '@/src/content/animals/ichthyosaur/images/preview-desktop-standard.webp'
import ichthyosaurPreviewDesktopWide from '@/src/content/animals/ichthyosaur/images/preview-desktop-wide.webp'
import ichthyosaurPreviewLandscapeCompact from '@/src/content/animals/ichthyosaur/images/preview-landscape-compact.webp'
import ichthyosaurPreviewPhoneCompact from '@/src/content/animals/ichthyosaur/images/preview-phone-compact.webp'
import ichthyosaurPreviewPhoneTall from '@/src/content/animals/ichthyosaur/images/preview-phone-tall.webp'
import ichthyosaurPreviewTabletPortrait from '@/src/content/animals/ichthyosaur/images/preview-tablet-portrait.webp'
import maiasauraPreviewDesktopStandard from '@/src/content/animals/maiasaura/images/preview-desktop-standard.webp'
import maiasauraPreviewDesktopWide from '@/src/content/animals/maiasaura/images/preview-desktop-wide.webp'
import maiasauraPreviewLandscapeCompact from '@/src/content/animals/maiasaura/images/preview-landscape-compact.webp'
import maiasauraPreviewPhoneCompact from '@/src/content/animals/maiasaura/images/preview-phone-compact.webp'
import maiasauraPreviewPhoneTall from '@/src/content/animals/maiasaura/images/preview-phone-tall.webp'
import maiasauraPreviewTabletPortrait from '@/src/content/animals/maiasaura/images/preview-tablet-portrait.webp'
import mammothPreviewDesktopStandard from '@/src/content/animals/mammoth/images/preview-desktop-standard.webp'
import mammothPreviewDesktopWide from '@/src/content/animals/mammoth/images/preview-desktop-wide.webp'
import mammothPreviewLandscapeCompact from '@/src/content/animals/mammoth/images/preview-landscape-compact.webp'
import mammothPreviewPhoneCompact from '@/src/content/animals/mammoth/images/preview-phone-compact.webp'
import mammothPreviewPhoneTall from '@/src/content/animals/mammoth/images/preview-phone-tall.webp'
import mammothPreviewTabletPortrait from '@/src/content/animals/mammoth/images/preview-tablet-portrait.webp'
import megalodonPreviewDesktopStandard from '@/src/content/animals/megalodon/images/preview-desktop-standard.webp'
import megalodonPreviewDesktopWide from '@/src/content/animals/megalodon/images/preview-desktop-wide.webp'
import megalodonPreviewLandscapeCompact from '@/src/content/animals/megalodon/images/preview-landscape-compact.webp'
import megalodonPreviewPhoneCompact from '@/src/content/animals/megalodon/images/preview-phone-compact.webp'
import megalodonPreviewPhoneTall from '@/src/content/animals/megalodon/images/preview-phone-tall.webp'
import megalodonPreviewTabletPortrait from '@/src/content/animals/megalodon/images/preview-tablet-portrait.webp'
import meganeuraPreviewDesktopStandard from '@/src/content/animals/meganeura/images/preview-desktop-standard.webp'
import meganeuraPreviewDesktopWide from '@/src/content/animals/meganeura/images/preview-desktop-wide.webp'
import meganeuraPreviewLandscapeCompact from '@/src/content/animals/meganeura/images/preview-landscape-compact.webp'
import meganeuraPreviewPhoneCompact from '@/src/content/animals/meganeura/images/preview-phone-compact.webp'
import meganeuraPreviewPhoneTall from '@/src/content/animals/meganeura/images/preview-phone-tall.webp'
import meganeuraPreviewTabletPortrait from '@/src/content/animals/meganeura/images/preview-tablet-portrait.webp'
import mosasaurusPreviewDesktopStandard from '@/src/content/animals/mosasaurus/images/preview-desktop-standard.webp'
import mosasaurusPreviewDesktopWide from '@/src/content/animals/mosasaurus/images/preview-desktop-wide.webp'
import mosasaurusPreviewLandscapeCompact from '@/src/content/animals/mosasaurus/images/preview-landscape-compact.webp'
import mosasaurusPreviewPhoneCompact from '@/src/content/animals/mosasaurus/images/preview-phone-compact.webp'
import mosasaurusPreviewPhoneTall from '@/src/content/animals/mosasaurus/images/preview-phone-tall.webp'
import mosasaurusPreviewTabletPortrait from '@/src/content/animals/mosasaurus/images/preview-tablet-portrait.webp'
import pachycephalosaurusPreviewDesktopStandard from '@/src/content/animals/pachycephalosaurus/images/preview-desktop-standard.webp'
import pachycephalosaurusPreviewDesktopWide from '@/src/content/animals/pachycephalosaurus/images/preview-desktop-wide.webp'
import pachycephalosaurusPreviewLandscapeCompact from '@/src/content/animals/pachycephalosaurus/images/preview-landscape-compact.webp'
import pachycephalosaurusPreviewPhoneCompact from '@/src/content/animals/pachycephalosaurus/images/preview-phone-compact.webp'
import pachycephalosaurusPreviewPhoneTall from '@/src/content/animals/pachycephalosaurus/images/preview-phone-tall.webp'
import pachycephalosaurusPreviewTabletPortrait from '@/src/content/animals/pachycephalosaurus/images/preview-tablet-portrait.webp'
import plesiosaurusPreviewDesktopStandard from '@/src/content/animals/plesiosaurus/images/preview-desktop-standard.webp'
import plesiosaurusPreviewDesktopWide from '@/src/content/animals/plesiosaurus/images/preview-desktop-wide.webp'
import plesiosaurusPreviewLandscapeCompact from '@/src/content/animals/plesiosaurus/images/preview-landscape-compact.webp'
import plesiosaurusPreviewPhoneCompact from '@/src/content/animals/plesiosaurus/images/preview-phone-compact.webp'
import plesiosaurusPreviewPhoneTall from '@/src/content/animals/plesiosaurus/images/preview-phone-tall.webp'
import plesiosaurusPreviewTabletPortrait from '@/src/content/animals/plesiosaurus/images/preview-tablet-portrait.webp'
import pteranodonPreviewDesktopStandard from '@/src/content/animals/pteranodon/images/preview-desktop-standard.webp'
import pteranodonPreviewDesktopWide from '@/src/content/animals/pteranodon/images/preview-desktop-wide.webp'
import pteranodonPreviewLandscapeCompact from '@/src/content/animals/pteranodon/images/preview-landscape-compact.webp'
import pteranodonPreviewPhoneCompact from '@/src/content/animals/pteranodon/images/preview-phone-compact.webp'
import pteranodonPreviewPhoneTall from '@/src/content/animals/pteranodon/images/preview-phone-tall.webp'
import pteranodonPreviewTabletPortrait from '@/src/content/animals/pteranodon/images/preview-tablet-portrait.webp'
import rhamphorhynchusPreviewDesktopStandard from '@/src/content/animals/rhamphorhynchus/images/preview-desktop-standard.webp'
import rhamphorhynchusPreviewDesktopWide from '@/src/content/animals/rhamphorhynchus/images/preview-desktop-wide.webp'
import rhamphorhynchusPreviewLandscapeCompact from '@/src/content/animals/rhamphorhynchus/images/preview-landscape-compact.webp'
import rhamphorhynchusPreviewPhoneCompact from '@/src/content/animals/rhamphorhynchus/images/preview-phone-compact.webp'
import rhamphorhynchusPreviewPhoneTall from '@/src/content/animals/rhamphorhynchus/images/preview-phone-tall.webp'
import rhamphorhynchusPreviewTabletPortrait from '@/src/content/animals/rhamphorhynchus/images/preview-tablet-portrait.webp'
import sauropeltaPreviewDesktopStandard from '@/src/content/animals/sauropelta/images/preview-desktop-standard.webp'
import sauropeltaPreviewDesktopWide from '@/src/content/animals/sauropelta/images/preview-desktop-wide.webp'
import sauropeltaPreviewLandscapeCompact from '@/src/content/animals/sauropelta/images/preview-landscape-compact.webp'
import sauropeltaPreviewPhoneCompact from '@/src/content/animals/sauropelta/images/preview-phone-compact.webp'
import sauropeltaPreviewPhoneTall from '@/src/content/animals/sauropelta/images/preview-phone-tall.webp'
import sauropeltaPreviewTabletPortrait from '@/src/content/animals/sauropelta/images/preview-tablet-portrait.webp'
import stegosaurusPreviewDesktopStandard from '@/src/content/animals/stegosaurus/images/preview-desktop-standard.webp'
import stegosaurusPreviewDesktopWide from '@/src/content/animals/stegosaurus/images/preview-desktop-wide.webp'
import stegosaurusPreviewLandscapeCompact from '@/src/content/animals/stegosaurus/images/preview-landscape-compact.webp'
import stegosaurusPreviewPhoneCompact from '@/src/content/animals/stegosaurus/images/preview-phone-compact.webp'
import stegosaurusPreviewPhoneTall from '@/src/content/animals/stegosaurus/images/preview-phone-tall.webp'
import stegosaurusPreviewTabletPortrait from '@/src/content/animals/stegosaurus/images/preview-tablet-portrait.webp'
import triceratopsPreviewDesktopStandard from '@/src/content/animals/triceratops/images/preview-desktop-standard.webp'
import triceratopsPreviewDesktopWide from '@/src/content/animals/triceratops/images/preview-desktop-wide.webp'
import triceratopsPreviewLandscapeCompact from '@/src/content/animals/triceratops/images/preview-landscape-compact.webp'
import triceratopsPreviewPhoneCompact from '@/src/content/animals/triceratops/images/preview-phone-compact.webp'
import triceratopsPreviewPhoneTall from '@/src/content/animals/triceratops/images/preview-phone-tall.webp'
import triceratopsPreviewTabletPortrait from '@/src/content/animals/triceratops/images/preview-tablet-portrait.webp'
import tupandactylusPreviewDesktopStandard from '@/src/content/animals/tupandactylus/images/preview-desktop-standard.webp'
import tupandactylusPreviewDesktopWide from '@/src/content/animals/tupandactylus/images/preview-desktop-wide.webp'
import tupandactylusPreviewLandscapeCompact from '@/src/content/animals/tupandactylus/images/preview-landscape-compact.webp'
import tupandactylusPreviewPhoneCompact from '@/src/content/animals/tupandactylus/images/preview-phone-compact.webp'
import tupandactylusPreviewPhoneTall from '@/src/content/animals/tupandactylus/images/preview-phone-tall.webp'
import tupandactylusPreviewTabletPortrait from '@/src/content/animals/tupandactylus/images/preview-tablet-portrait.webp'
import tyrannosaurusRexPreviewDesktopStandard from '@/src/content/animals/tyrannosaurus-rex/images/preview-desktop-standard.webp'
import tyrannosaurusRexPreviewDesktopWide from '@/src/content/animals/tyrannosaurus-rex/images/preview-desktop-wide.webp'
import tyrannosaurusRexPreviewLandscapeCompact from '@/src/content/animals/tyrannosaurus-rex/images/preview-landscape-compact.webp'
import tyrannosaurusRexPreviewPhoneCompact from '@/src/content/animals/tyrannosaurus-rex/images/preview-phone-compact.webp'
import tyrannosaurusRexPreviewPhoneTall from '@/src/content/animals/tyrannosaurus-rex/images/preview-phone-tall.webp'
import tyrannosaurusRexPreviewTabletPortrait from '@/src/content/animals/tyrannosaurus-rex/images/preview-tablet-portrait.webp'

export const modelPreviewModules: Readonly<Record<string, string>> = {
  '../content/animals/apatosaurus/images/preview-desktop-standard.webp': apatosaurusPreviewDesktopStandard.src,
  '../content/animals/apatosaurus/images/preview-desktop-wide.webp': apatosaurusPreviewDesktopWide.src,
  '../content/animals/apatosaurus/images/preview-landscape-compact.webp': apatosaurusPreviewLandscapeCompact.src,
  '../content/animals/apatosaurus/images/preview-phone-compact.webp': apatosaurusPreviewPhoneCompact.src,
  '../content/animals/apatosaurus/images/preview-phone-tall.webp': apatosaurusPreviewPhoneTall.src,
  '../content/animals/apatosaurus/images/preview-tablet-portrait.webp': apatosaurusPreviewTabletPortrait.src,
  '../content/animals/dilophosaurus/images/preview-desktop-standard.webp': dilophosaurusPreviewDesktopStandard.src,
  '../content/animals/dilophosaurus/images/preview-desktop-wide.webp': dilophosaurusPreviewDesktopWide.src,
  '../content/animals/dilophosaurus/images/preview-landscape-compact.webp': dilophosaurusPreviewLandscapeCompact.src,
  '../content/animals/dilophosaurus/images/preview-phone-compact.webp': dilophosaurusPreviewPhoneCompact.src,
  '../content/animals/dilophosaurus/images/preview-phone-tall.webp': dilophosaurusPreviewPhoneTall.src,
  '../content/animals/dilophosaurus/images/preview-tablet-portrait.webp': dilophosaurusPreviewTabletPortrait.src,
  '../content/animals/gigantoraptor/images/preview-desktop-standard.webp': gigantoraptorPreviewDesktopStandard.src,
  '../content/animals/gigantoraptor/images/preview-desktop-wide.webp': gigantoraptorPreviewDesktopWide.src,
  '../content/animals/gigantoraptor/images/preview-landscape-compact.webp': gigantoraptorPreviewLandscapeCompact.src,
  '../content/animals/gigantoraptor/images/preview-phone-compact.webp': gigantoraptorPreviewPhoneCompact.src,
  '../content/animals/gigantoraptor/images/preview-phone-tall.webp': gigantoraptorPreviewPhoneTall.src,
  '../content/animals/gigantoraptor/images/preview-tablet-portrait.webp': gigantoraptorPreviewTabletPortrait.src,
  '../content/animals/ichthyosaur/images/preview-desktop-standard.webp': ichthyosaurPreviewDesktopStandard.src,
  '../content/animals/ichthyosaur/images/preview-desktop-wide.webp': ichthyosaurPreviewDesktopWide.src,
  '../content/animals/ichthyosaur/images/preview-landscape-compact.webp': ichthyosaurPreviewLandscapeCompact.src,
  '../content/animals/ichthyosaur/images/preview-phone-compact.webp': ichthyosaurPreviewPhoneCompact.src,
  '../content/animals/ichthyosaur/images/preview-phone-tall.webp': ichthyosaurPreviewPhoneTall.src,
  '../content/animals/ichthyosaur/images/preview-tablet-portrait.webp': ichthyosaurPreviewTabletPortrait.src,
  '../content/animals/maiasaura/images/preview-desktop-standard.webp': maiasauraPreviewDesktopStandard.src,
  '../content/animals/maiasaura/images/preview-desktop-wide.webp': maiasauraPreviewDesktopWide.src,
  '../content/animals/maiasaura/images/preview-landscape-compact.webp': maiasauraPreviewLandscapeCompact.src,
  '../content/animals/maiasaura/images/preview-phone-compact.webp': maiasauraPreviewPhoneCompact.src,
  '../content/animals/maiasaura/images/preview-phone-tall.webp': maiasauraPreviewPhoneTall.src,
  '../content/animals/maiasaura/images/preview-tablet-portrait.webp': maiasauraPreviewTabletPortrait.src,
  '../content/animals/mammoth/images/preview-desktop-standard.webp': mammothPreviewDesktopStandard.src,
  '../content/animals/mammoth/images/preview-desktop-wide.webp': mammothPreviewDesktopWide.src,
  '../content/animals/mammoth/images/preview-landscape-compact.webp': mammothPreviewLandscapeCompact.src,
  '../content/animals/mammoth/images/preview-phone-compact.webp': mammothPreviewPhoneCompact.src,
  '../content/animals/mammoth/images/preview-phone-tall.webp': mammothPreviewPhoneTall.src,
  '../content/animals/mammoth/images/preview-tablet-portrait.webp': mammothPreviewTabletPortrait.src,
  '../content/animals/megalodon/images/preview-desktop-standard.webp': megalodonPreviewDesktopStandard.src,
  '../content/animals/megalodon/images/preview-desktop-wide.webp': megalodonPreviewDesktopWide.src,
  '../content/animals/megalodon/images/preview-landscape-compact.webp': megalodonPreviewLandscapeCompact.src,
  '../content/animals/megalodon/images/preview-phone-compact.webp': megalodonPreviewPhoneCompact.src,
  '../content/animals/megalodon/images/preview-phone-tall.webp': megalodonPreviewPhoneTall.src,
  '../content/animals/megalodon/images/preview-tablet-portrait.webp': megalodonPreviewTabletPortrait.src,
  '../content/animals/meganeura/images/preview-desktop-standard.webp': meganeuraPreviewDesktopStandard.src,
  '../content/animals/meganeura/images/preview-desktop-wide.webp': meganeuraPreviewDesktopWide.src,
  '../content/animals/meganeura/images/preview-landscape-compact.webp': meganeuraPreviewLandscapeCompact.src,
  '../content/animals/meganeura/images/preview-phone-compact.webp': meganeuraPreviewPhoneCompact.src,
  '../content/animals/meganeura/images/preview-phone-tall.webp': meganeuraPreviewPhoneTall.src,
  '../content/animals/meganeura/images/preview-tablet-portrait.webp': meganeuraPreviewTabletPortrait.src,
  '../content/animals/mosasaurus/images/preview-desktop-standard.webp': mosasaurusPreviewDesktopStandard.src,
  '../content/animals/mosasaurus/images/preview-desktop-wide.webp': mosasaurusPreviewDesktopWide.src,
  '../content/animals/mosasaurus/images/preview-landscape-compact.webp': mosasaurusPreviewLandscapeCompact.src,
  '../content/animals/mosasaurus/images/preview-phone-compact.webp': mosasaurusPreviewPhoneCompact.src,
  '../content/animals/mosasaurus/images/preview-phone-tall.webp': mosasaurusPreviewPhoneTall.src,
  '../content/animals/mosasaurus/images/preview-tablet-portrait.webp': mosasaurusPreviewTabletPortrait.src,
  '../content/animals/pachycephalosaurus/images/preview-desktop-standard.webp': pachycephalosaurusPreviewDesktopStandard.src,
  '../content/animals/pachycephalosaurus/images/preview-desktop-wide.webp': pachycephalosaurusPreviewDesktopWide.src,
  '../content/animals/pachycephalosaurus/images/preview-landscape-compact.webp': pachycephalosaurusPreviewLandscapeCompact.src,
  '../content/animals/pachycephalosaurus/images/preview-phone-compact.webp': pachycephalosaurusPreviewPhoneCompact.src,
  '../content/animals/pachycephalosaurus/images/preview-phone-tall.webp': pachycephalosaurusPreviewPhoneTall.src,
  '../content/animals/pachycephalosaurus/images/preview-tablet-portrait.webp': pachycephalosaurusPreviewTabletPortrait.src,
  '../content/animals/plesiosaurus/images/preview-desktop-standard.webp': plesiosaurusPreviewDesktopStandard.src,
  '../content/animals/plesiosaurus/images/preview-desktop-wide.webp': plesiosaurusPreviewDesktopWide.src,
  '../content/animals/plesiosaurus/images/preview-landscape-compact.webp': plesiosaurusPreviewLandscapeCompact.src,
  '../content/animals/plesiosaurus/images/preview-phone-compact.webp': plesiosaurusPreviewPhoneCompact.src,
  '../content/animals/plesiosaurus/images/preview-phone-tall.webp': plesiosaurusPreviewPhoneTall.src,
  '../content/animals/plesiosaurus/images/preview-tablet-portrait.webp': plesiosaurusPreviewTabletPortrait.src,
  '../content/animals/pteranodon/images/preview-desktop-standard.webp': pteranodonPreviewDesktopStandard.src,
  '../content/animals/pteranodon/images/preview-desktop-wide.webp': pteranodonPreviewDesktopWide.src,
  '../content/animals/pteranodon/images/preview-landscape-compact.webp': pteranodonPreviewLandscapeCompact.src,
  '../content/animals/pteranodon/images/preview-phone-compact.webp': pteranodonPreviewPhoneCompact.src,
  '../content/animals/pteranodon/images/preview-phone-tall.webp': pteranodonPreviewPhoneTall.src,
  '../content/animals/pteranodon/images/preview-tablet-portrait.webp': pteranodonPreviewTabletPortrait.src,
  '../content/animals/rhamphorhynchus/images/preview-desktop-standard.webp': rhamphorhynchusPreviewDesktopStandard.src,
  '../content/animals/rhamphorhynchus/images/preview-desktop-wide.webp': rhamphorhynchusPreviewDesktopWide.src,
  '../content/animals/rhamphorhynchus/images/preview-landscape-compact.webp': rhamphorhynchusPreviewLandscapeCompact.src,
  '../content/animals/rhamphorhynchus/images/preview-phone-compact.webp': rhamphorhynchusPreviewPhoneCompact.src,
  '../content/animals/rhamphorhynchus/images/preview-phone-tall.webp': rhamphorhynchusPreviewPhoneTall.src,
  '../content/animals/rhamphorhynchus/images/preview-tablet-portrait.webp': rhamphorhynchusPreviewTabletPortrait.src,
  '../content/animals/sauropelta/images/preview-desktop-standard.webp': sauropeltaPreviewDesktopStandard.src,
  '../content/animals/sauropelta/images/preview-desktop-wide.webp': sauropeltaPreviewDesktopWide.src,
  '../content/animals/sauropelta/images/preview-landscape-compact.webp': sauropeltaPreviewLandscapeCompact.src,
  '../content/animals/sauropelta/images/preview-phone-compact.webp': sauropeltaPreviewPhoneCompact.src,
  '../content/animals/sauropelta/images/preview-phone-tall.webp': sauropeltaPreviewPhoneTall.src,
  '../content/animals/sauropelta/images/preview-tablet-portrait.webp': sauropeltaPreviewTabletPortrait.src,
  '../content/animals/stegosaurus/images/preview-desktop-standard.webp': stegosaurusPreviewDesktopStandard.src,
  '../content/animals/stegosaurus/images/preview-desktop-wide.webp': stegosaurusPreviewDesktopWide.src,
  '../content/animals/stegosaurus/images/preview-landscape-compact.webp': stegosaurusPreviewLandscapeCompact.src,
  '../content/animals/stegosaurus/images/preview-phone-compact.webp': stegosaurusPreviewPhoneCompact.src,
  '../content/animals/stegosaurus/images/preview-phone-tall.webp': stegosaurusPreviewPhoneTall.src,
  '../content/animals/stegosaurus/images/preview-tablet-portrait.webp': stegosaurusPreviewTabletPortrait.src,
  '../content/animals/triceratops/images/preview-desktop-standard.webp': triceratopsPreviewDesktopStandard.src,
  '../content/animals/triceratops/images/preview-desktop-wide.webp': triceratopsPreviewDesktopWide.src,
  '../content/animals/triceratops/images/preview-landscape-compact.webp': triceratopsPreviewLandscapeCompact.src,
  '../content/animals/triceratops/images/preview-phone-compact.webp': triceratopsPreviewPhoneCompact.src,
  '../content/animals/triceratops/images/preview-phone-tall.webp': triceratopsPreviewPhoneTall.src,
  '../content/animals/triceratops/images/preview-tablet-portrait.webp': triceratopsPreviewTabletPortrait.src,
  '../content/animals/tupandactylus/images/preview-desktop-standard.webp': tupandactylusPreviewDesktopStandard.src,
  '../content/animals/tupandactylus/images/preview-desktop-wide.webp': tupandactylusPreviewDesktopWide.src,
  '../content/animals/tupandactylus/images/preview-landscape-compact.webp': tupandactylusPreviewLandscapeCompact.src,
  '../content/animals/tupandactylus/images/preview-phone-compact.webp': tupandactylusPreviewPhoneCompact.src,
  '../content/animals/tupandactylus/images/preview-phone-tall.webp': tupandactylusPreviewPhoneTall.src,
  '../content/animals/tupandactylus/images/preview-tablet-portrait.webp': tupandactylusPreviewTabletPortrait.src,
  '../content/animals/tyrannosaurus-rex/images/preview-desktop-standard.webp': tyrannosaurusRexPreviewDesktopStandard.src,
  '../content/animals/tyrannosaurus-rex/images/preview-desktop-wide.webp': tyrannosaurusRexPreviewDesktopWide.src,
  '../content/animals/tyrannosaurus-rex/images/preview-landscape-compact.webp': tyrannosaurusRexPreviewLandscapeCompact.src,
  '../content/animals/tyrannosaurus-rex/images/preview-phone-compact.webp': tyrannosaurusRexPreviewPhoneCompact.src,
  '../content/animals/tyrannosaurus-rex/images/preview-phone-tall.webp': tyrannosaurusRexPreviewPhoneTall.src,
  '../content/animals/tyrannosaurus-rex/images/preview-tablet-portrait.webp': tyrannosaurusRexPreviewTabletPortrait.src,
}
