// Generated by npm run generate:registry. Do not edit by hand.
import apatosaurusPreviewDesktopStandard from '../content/animals/apatosaurus/images/preview-desktop-standard.webp'
import apatosaurusPreviewDesktopWide from '../content/animals/apatosaurus/images/preview-desktop-wide.webp'
import apatosaurusPreviewLandscapeCompact from '../content/animals/apatosaurus/images/preview-landscape-compact.webp'
import apatosaurusPreviewPhoneCompact from '../content/animals/apatosaurus/images/preview-phone-compact.webp'
import apatosaurusPreviewPhoneTall from '../content/animals/apatosaurus/images/preview-phone-tall.webp'
import apatosaurusPreviewTabletPortrait from '../content/animals/apatosaurus/images/preview-tablet-portrait.webp'
import dilophosaurusPreviewDesktopStandard from '../content/animals/dilophosaurus/images/preview-desktop-standard.webp'
import dilophosaurusPreviewDesktopWide from '../content/animals/dilophosaurus/images/preview-desktop-wide.webp'
import dilophosaurusPreviewLandscapeCompact from '../content/animals/dilophosaurus/images/preview-landscape-compact.webp'
import dilophosaurusPreviewPhoneCompact from '../content/animals/dilophosaurus/images/preview-phone-compact.webp'
import dilophosaurusPreviewPhoneTall from '../content/animals/dilophosaurus/images/preview-phone-tall.webp'
import dilophosaurusPreviewTabletPortrait from '../content/animals/dilophosaurus/images/preview-tablet-portrait.webp'
import gigantoraptorPreviewDesktopStandard from '../content/animals/gigantoraptor/images/preview-desktop-standard.webp'
import gigantoraptorPreviewDesktopWide from '../content/animals/gigantoraptor/images/preview-desktop-wide.webp'
import gigantoraptorPreviewLandscapeCompact from '../content/animals/gigantoraptor/images/preview-landscape-compact.webp'
import gigantoraptorPreviewPhoneCompact from '../content/animals/gigantoraptor/images/preview-phone-compact.webp'
import gigantoraptorPreviewPhoneTall from '../content/animals/gigantoraptor/images/preview-phone-tall.webp'
import gigantoraptorPreviewTabletPortrait from '../content/animals/gigantoraptor/images/preview-tablet-portrait.webp'
import ichthyosaurPreviewDesktopStandard from '../content/animals/ichthyosaur/images/preview-desktop-standard.webp'
import ichthyosaurPreviewDesktopWide from '../content/animals/ichthyosaur/images/preview-desktop-wide.webp'
import ichthyosaurPreviewLandscapeCompact from '../content/animals/ichthyosaur/images/preview-landscape-compact.webp'
import ichthyosaurPreviewPhoneCompact from '../content/animals/ichthyosaur/images/preview-phone-compact.webp'
import ichthyosaurPreviewPhoneTall from '../content/animals/ichthyosaur/images/preview-phone-tall.webp'
import ichthyosaurPreviewTabletPortrait from '../content/animals/ichthyosaur/images/preview-tablet-portrait.webp'
import maiasauraPreviewDesktopStandard from '../content/animals/maiasaura/images/preview-desktop-standard.webp'
import maiasauraPreviewDesktopWide from '../content/animals/maiasaura/images/preview-desktop-wide.webp'
import maiasauraPreviewLandscapeCompact from '../content/animals/maiasaura/images/preview-landscape-compact.webp'
import maiasauraPreviewPhoneCompact from '../content/animals/maiasaura/images/preview-phone-compact.webp'
import maiasauraPreviewPhoneTall from '../content/animals/maiasaura/images/preview-phone-tall.webp'
import maiasauraPreviewTabletPortrait from '../content/animals/maiasaura/images/preview-tablet-portrait.webp'
import mammothPreviewDesktopStandard from '../content/animals/mammoth/images/preview-desktop-standard.webp'
import mammothPreviewDesktopWide from '../content/animals/mammoth/images/preview-desktop-wide.webp'
import mammothPreviewLandscapeCompact from '../content/animals/mammoth/images/preview-landscape-compact.webp'
import mammothPreviewPhoneCompact from '../content/animals/mammoth/images/preview-phone-compact.webp'
import mammothPreviewPhoneTall from '../content/animals/mammoth/images/preview-phone-tall.webp'
import mammothPreviewTabletPortrait from '../content/animals/mammoth/images/preview-tablet-portrait.webp'
import megalodonPreviewDesktopStandard from '../content/animals/megalodon/images/preview-desktop-standard.webp'
import megalodonPreviewDesktopWide from '../content/animals/megalodon/images/preview-desktop-wide.webp'
import megalodonPreviewLandscapeCompact from '../content/animals/megalodon/images/preview-landscape-compact.webp'
import megalodonPreviewPhoneCompact from '../content/animals/megalodon/images/preview-phone-compact.webp'
import megalodonPreviewPhoneTall from '../content/animals/megalodon/images/preview-phone-tall.webp'
import megalodonPreviewTabletPortrait from '../content/animals/megalodon/images/preview-tablet-portrait.webp'
import meganeuraPreviewDesktopStandard from '../content/animals/meganeura/images/preview-desktop-standard.webp'
import meganeuraPreviewDesktopWide from '../content/animals/meganeura/images/preview-desktop-wide.webp'
import meganeuraPreviewLandscapeCompact from '../content/animals/meganeura/images/preview-landscape-compact.webp'
import meganeuraPreviewPhoneCompact from '../content/animals/meganeura/images/preview-phone-compact.webp'
import meganeuraPreviewPhoneTall from '../content/animals/meganeura/images/preview-phone-tall.webp'
import meganeuraPreviewTabletPortrait from '../content/animals/meganeura/images/preview-tablet-portrait.webp'
import mosasaurusPreviewDesktopStandard from '../content/animals/mosasaurus/images/preview-desktop-standard.webp'
import mosasaurusPreviewDesktopWide from '../content/animals/mosasaurus/images/preview-desktop-wide.webp'
import mosasaurusPreviewLandscapeCompact from '../content/animals/mosasaurus/images/preview-landscape-compact.webp'
import mosasaurusPreviewPhoneCompact from '../content/animals/mosasaurus/images/preview-phone-compact.webp'
import mosasaurusPreviewPhoneTall from '../content/animals/mosasaurus/images/preview-phone-tall.webp'
import mosasaurusPreviewTabletPortrait from '../content/animals/mosasaurus/images/preview-tablet-portrait.webp'
import pachycephalosaurusPreviewDesktopStandard from '../content/animals/pachycephalosaurus/images/preview-desktop-standard.webp'
import pachycephalosaurusPreviewDesktopWide from '../content/animals/pachycephalosaurus/images/preview-desktop-wide.webp'
import pachycephalosaurusPreviewLandscapeCompact from '../content/animals/pachycephalosaurus/images/preview-landscape-compact.webp'
import pachycephalosaurusPreviewPhoneCompact from '../content/animals/pachycephalosaurus/images/preview-phone-compact.webp'
import pachycephalosaurusPreviewPhoneTall from '../content/animals/pachycephalosaurus/images/preview-phone-tall.webp'
import pachycephalosaurusPreviewTabletPortrait from '../content/animals/pachycephalosaurus/images/preview-tablet-portrait.webp'
import plesiosaurusPreviewDesktopStandard from '../content/animals/plesiosaurus/images/preview-desktop-standard.webp'
import plesiosaurusPreviewDesktopWide from '../content/animals/plesiosaurus/images/preview-desktop-wide.webp'
import plesiosaurusPreviewLandscapeCompact from '../content/animals/plesiosaurus/images/preview-landscape-compact.webp'
import plesiosaurusPreviewPhoneCompact from '../content/animals/plesiosaurus/images/preview-phone-compact.webp'
import plesiosaurusPreviewPhoneTall from '../content/animals/plesiosaurus/images/preview-phone-tall.webp'
import plesiosaurusPreviewTabletPortrait from '../content/animals/plesiosaurus/images/preview-tablet-portrait.webp'
import pteranodonPreviewDesktopStandard from '../content/animals/pteranodon/images/preview-desktop-standard.webp'
import pteranodonPreviewDesktopWide from '../content/animals/pteranodon/images/preview-desktop-wide.webp'
import pteranodonPreviewLandscapeCompact from '../content/animals/pteranodon/images/preview-landscape-compact.webp'
import pteranodonPreviewPhoneCompact from '../content/animals/pteranodon/images/preview-phone-compact.webp'
import pteranodonPreviewPhoneTall from '../content/animals/pteranodon/images/preview-phone-tall.webp'
import pteranodonPreviewTabletPortrait from '../content/animals/pteranodon/images/preview-tablet-portrait.webp'
import rhamphorhynchusPreviewDesktopStandard from '../content/animals/rhamphorhynchus/images/preview-desktop-standard.webp'
import rhamphorhynchusPreviewDesktopWide from '../content/animals/rhamphorhynchus/images/preview-desktop-wide.webp'
import rhamphorhynchusPreviewLandscapeCompact from '../content/animals/rhamphorhynchus/images/preview-landscape-compact.webp'
import rhamphorhynchusPreviewPhoneCompact from '../content/animals/rhamphorhynchus/images/preview-phone-compact.webp'
import rhamphorhynchusPreviewPhoneTall from '../content/animals/rhamphorhynchus/images/preview-phone-tall.webp'
import rhamphorhynchusPreviewTabletPortrait from '../content/animals/rhamphorhynchus/images/preview-tablet-portrait.webp'
import sauropeltaPreviewDesktopStandard from '../content/animals/sauropelta/images/preview-desktop-standard.webp'
import sauropeltaPreviewDesktopWide from '../content/animals/sauropelta/images/preview-desktop-wide.webp'
import sauropeltaPreviewLandscapeCompact from '../content/animals/sauropelta/images/preview-landscape-compact.webp'
import sauropeltaPreviewPhoneCompact from '../content/animals/sauropelta/images/preview-phone-compact.webp'
import sauropeltaPreviewPhoneTall from '../content/animals/sauropelta/images/preview-phone-tall.webp'
import sauropeltaPreviewTabletPortrait from '../content/animals/sauropelta/images/preview-tablet-portrait.webp'
import stegosaurusPreviewDesktopStandard from '../content/animals/stegosaurus/images/preview-desktop-standard.webp'
import stegosaurusPreviewDesktopWide from '../content/animals/stegosaurus/images/preview-desktop-wide.webp'
import stegosaurusPreviewLandscapeCompact from '../content/animals/stegosaurus/images/preview-landscape-compact.webp'
import stegosaurusPreviewPhoneCompact from '../content/animals/stegosaurus/images/preview-phone-compact.webp'
import stegosaurusPreviewPhoneTall from '../content/animals/stegosaurus/images/preview-phone-tall.webp'
import stegosaurusPreviewTabletPortrait from '../content/animals/stegosaurus/images/preview-tablet-portrait.webp'
import triceratopsPreviewDesktopStandard from '../content/animals/triceratops/images/preview-desktop-standard.webp'
import triceratopsPreviewDesktopWide from '../content/animals/triceratops/images/preview-desktop-wide.webp'
import triceratopsPreviewLandscapeCompact from '../content/animals/triceratops/images/preview-landscape-compact.webp'
import triceratopsPreviewPhoneCompact from '../content/animals/triceratops/images/preview-phone-compact.webp'
import triceratopsPreviewPhoneTall from '../content/animals/triceratops/images/preview-phone-tall.webp'
import triceratopsPreviewTabletPortrait from '../content/animals/triceratops/images/preview-tablet-portrait.webp'
import tupandactylusPreviewDesktopStandard from '../content/animals/tupandactylus/images/preview-desktop-standard.webp'
import tupandactylusPreviewDesktopWide from '../content/animals/tupandactylus/images/preview-desktop-wide.webp'
import tupandactylusPreviewLandscapeCompact from '../content/animals/tupandactylus/images/preview-landscape-compact.webp'
import tupandactylusPreviewPhoneCompact from '../content/animals/tupandactylus/images/preview-phone-compact.webp'
import tupandactylusPreviewPhoneTall from '../content/animals/tupandactylus/images/preview-phone-tall.webp'
import tupandactylusPreviewTabletPortrait from '../content/animals/tupandactylus/images/preview-tablet-portrait.webp'
import tyrannosaurusRexPreviewDesktopStandard from '../content/animals/tyrannosaurus-rex/images/preview-desktop-standard.webp'
import tyrannosaurusRexPreviewDesktopWide from '../content/animals/tyrannosaurus-rex/images/preview-desktop-wide.webp'
import tyrannosaurusRexPreviewLandscapeCompact from '../content/animals/tyrannosaurus-rex/images/preview-landscape-compact.webp'
import tyrannosaurusRexPreviewPhoneCompact from '../content/animals/tyrannosaurus-rex/images/preview-phone-compact.webp'
import tyrannosaurusRexPreviewPhoneTall from '../content/animals/tyrannosaurus-rex/images/preview-phone-tall.webp'
import tyrannosaurusRexPreviewTabletPortrait from '../content/animals/tyrannosaurus-rex/images/preview-tablet-portrait.webp'

export const modelPreviewModules: Readonly<Record<string, string>> = {
  '../content/animals/apatosaurus/images/preview-desktop-standard.webp': apatosaurusPreviewDesktopStandard.src,
  '../content/animals/apatosaurus/images/preview-desktop-wide.webp': apatosaurusPreviewDesktopWide.src,
  '../content/animals/apatosaurus/images/preview-landscape-compact.webp': apatosaurusPreviewLandscapeCompact.src,
  '../content/animals/apatosaurus/images/preview-phone-compact.webp': apatosaurusPreviewPhoneCompact.src,
  '../content/animals/apatosaurus/images/preview-phone-tall.webp': apatosaurusPreviewPhoneTall.src,
  '../content/animals/apatosaurus/images/preview-tablet-portrait.webp': apatosaurusPreviewTabletPortrait.src,
  '../content/animals/dilophosaurus/images/preview-desktop-standard.webp': dilophosaurusPreviewDesktopStandard.src,
  '../content/animals/dilophosaurus/images/preview-desktop-wide.webp': dilophosaurusPreviewDesktopWide.src,
  '../content/animals/dilophosaurus/images/preview-landscape-compact.webp': dilophosaurusPreviewLandscapeCompact.src,
  '../content/animals/dilophosaurus/images/preview-phone-compact.webp': dilophosaurusPreviewPhoneCompact.src,
  '../content/animals/dilophosaurus/images/preview-phone-tall.webp': dilophosaurusPreviewPhoneTall.src,
  '../content/animals/dilophosaurus/images/preview-tablet-portrait.webp': dilophosaurusPreviewTabletPortrait.src,
  '../content/animals/gigantoraptor/images/preview-desktop-standard.webp': gigantoraptorPreviewDesktopStandard.src,
  '../content/animals/gigantoraptor/images/preview-desktop-wide.webp': gigantoraptorPreviewDesktopWide.src,
  '../content/animals/gigantoraptor/images/preview-landscape-compact.webp': gigantoraptorPreviewLandscapeCompact.src,
  '../content/animals/gigantoraptor/images/preview-phone-compact.webp': gigantoraptorPreviewPhoneCompact.src,
  '../content/animals/gigantoraptor/images/preview-phone-tall.webp': gigantoraptorPreviewPhoneTall.src,
  '../content/animals/gigantoraptor/images/preview-tablet-portrait.webp': gigantoraptorPreviewTabletPortrait.src,
  '../content/animals/ichthyosaur/images/preview-desktop-standard.webp': ichthyosaurPreviewDesktopStandard.src,
  '../content/animals/ichthyosaur/images/preview-desktop-wide.webp': ichthyosaurPreviewDesktopWide.src,
  '../content/animals/ichthyosaur/images/preview-landscape-compact.webp': ichthyosaurPreviewLandscapeCompact.src,
  '../content/animals/ichthyosaur/images/preview-phone-compact.webp': ichthyosaurPreviewPhoneCompact.src,
  '../content/animals/ichthyosaur/images/preview-phone-tall.webp': ichthyosaurPreviewPhoneTall.src,
  '../content/animals/ichthyosaur/images/preview-tablet-portrait.webp': ichthyosaurPreviewTabletPortrait.src,
  '../content/animals/maiasaura/images/preview-desktop-standard.webp': maiasauraPreviewDesktopStandard.src,
  '../content/animals/maiasaura/images/preview-desktop-wide.webp': maiasauraPreviewDesktopWide.src,
  '../content/animals/maiasaura/images/preview-landscape-compact.webp': maiasauraPreviewLandscapeCompact.src,
  '../content/animals/maiasaura/images/preview-phone-compact.webp': maiasauraPreviewPhoneCompact.src,
  '../content/animals/maiasaura/images/preview-phone-tall.webp': maiasauraPreviewPhoneTall.src,
  '../content/animals/maiasaura/images/preview-tablet-portrait.webp': maiasauraPreviewTabletPortrait.src,
  '../content/animals/mammoth/images/preview-desktop-standard.webp': mammothPreviewDesktopStandard.src,
  '../content/animals/mammoth/images/preview-desktop-wide.webp': mammothPreviewDesktopWide.src,
  '../content/animals/mammoth/images/preview-landscape-compact.webp': mammothPreviewLandscapeCompact.src,
  '../content/animals/mammoth/images/preview-phone-compact.webp': mammothPreviewPhoneCompact.src,
  '../content/animals/mammoth/images/preview-phone-tall.webp': mammothPreviewPhoneTall.src,
  '../content/animals/mammoth/images/preview-tablet-portrait.webp': mammothPreviewTabletPortrait.src,
  '../content/animals/megalodon/images/preview-desktop-standard.webp': megalodonPreviewDesktopStandard.src,
  '../content/animals/megalodon/images/preview-desktop-wide.webp': megalodonPreviewDesktopWide.src,
  '../content/animals/megalodon/images/preview-landscape-compact.webp': megalodonPreviewLandscapeCompact.src,
  '../content/animals/megalodon/images/preview-phone-compact.webp': megalodonPreviewPhoneCompact.src,
  '../content/animals/megalodon/images/preview-phone-tall.webp': megalodonPreviewPhoneTall.src,
  '../content/animals/megalodon/images/preview-tablet-portrait.webp': megalodonPreviewTabletPortrait.src,
  '../content/animals/meganeura/images/preview-desktop-standard.webp': meganeuraPreviewDesktopStandard.src,
  '../content/animals/meganeura/images/preview-desktop-wide.webp': meganeuraPreviewDesktopWide.src,
  '../content/animals/meganeura/images/preview-landscape-compact.webp': meganeuraPreviewLandscapeCompact.src,
  '../content/animals/meganeura/images/preview-phone-compact.webp': meganeuraPreviewPhoneCompact.src,
  '../content/animals/meganeura/images/preview-phone-tall.webp': meganeuraPreviewPhoneTall.src,
  '../content/animals/meganeura/images/preview-tablet-portrait.webp': meganeuraPreviewTabletPortrait.src,
  '../content/animals/mosasaurus/images/preview-desktop-standard.webp': mosasaurusPreviewDesktopStandard.src,
  '../content/animals/mosasaurus/images/preview-desktop-wide.webp': mosasaurusPreviewDesktopWide.src,
  '../content/animals/mosasaurus/images/preview-landscape-compact.webp': mosasaurusPreviewLandscapeCompact.src,
  '../content/animals/mosasaurus/images/preview-phone-compact.webp': mosasaurusPreviewPhoneCompact.src,
  '../content/animals/mosasaurus/images/preview-phone-tall.webp': mosasaurusPreviewPhoneTall.src,
  '../content/animals/mosasaurus/images/preview-tablet-portrait.webp': mosasaurusPreviewTabletPortrait.src,
  '../content/animals/pachycephalosaurus/images/preview-desktop-standard.webp': pachycephalosaurusPreviewDesktopStandard.src,
  '../content/animals/pachycephalosaurus/images/preview-desktop-wide.webp': pachycephalosaurusPreviewDesktopWide.src,
  '../content/animals/pachycephalosaurus/images/preview-landscape-compact.webp': pachycephalosaurusPreviewLandscapeCompact.src,
  '../content/animals/pachycephalosaurus/images/preview-phone-compact.webp': pachycephalosaurusPreviewPhoneCompact.src,
  '../content/animals/pachycephalosaurus/images/preview-phone-tall.webp': pachycephalosaurusPreviewPhoneTall.src,
  '../content/animals/pachycephalosaurus/images/preview-tablet-portrait.webp': pachycephalosaurusPreviewTabletPortrait.src,
  '../content/animals/plesiosaurus/images/preview-desktop-standard.webp': plesiosaurusPreviewDesktopStandard.src,
  '../content/animals/plesiosaurus/images/preview-desktop-wide.webp': plesiosaurusPreviewDesktopWide.src,
  '../content/animals/plesiosaurus/images/preview-landscape-compact.webp': plesiosaurusPreviewLandscapeCompact.src,
  '../content/animals/plesiosaurus/images/preview-phone-compact.webp': plesiosaurusPreviewPhoneCompact.src,
  '../content/animals/plesiosaurus/images/preview-phone-tall.webp': plesiosaurusPreviewPhoneTall.src,
  '../content/animals/plesiosaurus/images/preview-tablet-portrait.webp': plesiosaurusPreviewTabletPortrait.src,
  '../content/animals/pteranodon/images/preview-desktop-standard.webp': pteranodonPreviewDesktopStandard.src,
  '../content/animals/pteranodon/images/preview-desktop-wide.webp': pteranodonPreviewDesktopWide.src,
  '../content/animals/pteranodon/images/preview-landscape-compact.webp': pteranodonPreviewLandscapeCompact.src,
  '../content/animals/pteranodon/images/preview-phone-compact.webp': pteranodonPreviewPhoneCompact.src,
  '../content/animals/pteranodon/images/preview-phone-tall.webp': pteranodonPreviewPhoneTall.src,
  '../content/animals/pteranodon/images/preview-tablet-portrait.webp': pteranodonPreviewTabletPortrait.src,
  '../content/animals/rhamphorhynchus/images/preview-desktop-standard.webp': rhamphorhynchusPreviewDesktopStandard.src,
  '../content/animals/rhamphorhynchus/images/preview-desktop-wide.webp': rhamphorhynchusPreviewDesktopWide.src,
  '../content/animals/rhamphorhynchus/images/preview-landscape-compact.webp': rhamphorhynchusPreviewLandscapeCompact.src,
  '../content/animals/rhamphorhynchus/images/preview-phone-compact.webp': rhamphorhynchusPreviewPhoneCompact.src,
  '../content/animals/rhamphorhynchus/images/preview-phone-tall.webp': rhamphorhynchusPreviewPhoneTall.src,
  '../content/animals/rhamphorhynchus/images/preview-tablet-portrait.webp': rhamphorhynchusPreviewTabletPortrait.src,
  '../content/animals/sauropelta/images/preview-desktop-standard.webp': sauropeltaPreviewDesktopStandard.src,
  '../content/animals/sauropelta/images/preview-desktop-wide.webp': sauropeltaPreviewDesktopWide.src,
  '../content/animals/sauropelta/images/preview-landscape-compact.webp': sauropeltaPreviewLandscapeCompact.src,
  '../content/animals/sauropelta/images/preview-phone-compact.webp': sauropeltaPreviewPhoneCompact.src,
  '../content/animals/sauropelta/images/preview-phone-tall.webp': sauropeltaPreviewPhoneTall.src,
  '../content/animals/sauropelta/images/preview-tablet-portrait.webp': sauropeltaPreviewTabletPortrait.src,
  '../content/animals/stegosaurus/images/preview-desktop-standard.webp': stegosaurusPreviewDesktopStandard.src,
  '../content/animals/stegosaurus/images/preview-desktop-wide.webp': stegosaurusPreviewDesktopWide.src,
  '../content/animals/stegosaurus/images/preview-landscape-compact.webp': stegosaurusPreviewLandscapeCompact.src,
  '../content/animals/stegosaurus/images/preview-phone-compact.webp': stegosaurusPreviewPhoneCompact.src,
  '../content/animals/stegosaurus/images/preview-phone-tall.webp': stegosaurusPreviewPhoneTall.src,
  '../content/animals/stegosaurus/images/preview-tablet-portrait.webp': stegosaurusPreviewTabletPortrait.src,
  '../content/animals/triceratops/images/preview-desktop-standard.webp': triceratopsPreviewDesktopStandard.src,
  '../content/animals/triceratops/images/preview-desktop-wide.webp': triceratopsPreviewDesktopWide.src,
  '../content/animals/triceratops/images/preview-landscape-compact.webp': triceratopsPreviewLandscapeCompact.src,
  '../content/animals/triceratops/images/preview-phone-compact.webp': triceratopsPreviewPhoneCompact.src,
  '../content/animals/triceratops/images/preview-phone-tall.webp': triceratopsPreviewPhoneTall.src,
  '../content/animals/triceratops/images/preview-tablet-portrait.webp': triceratopsPreviewTabletPortrait.src,
  '../content/animals/tupandactylus/images/preview-desktop-standard.webp': tupandactylusPreviewDesktopStandard.src,
  '../content/animals/tupandactylus/images/preview-desktop-wide.webp': tupandactylusPreviewDesktopWide.src,
  '../content/animals/tupandactylus/images/preview-landscape-compact.webp': tupandactylusPreviewLandscapeCompact.src,
  '../content/animals/tupandactylus/images/preview-phone-compact.webp': tupandactylusPreviewPhoneCompact.src,
  '../content/animals/tupandactylus/images/preview-phone-tall.webp': tupandactylusPreviewPhoneTall.src,
  '../content/animals/tupandactylus/images/preview-tablet-portrait.webp': tupandactylusPreviewTabletPortrait.src,
  '../content/animals/tyrannosaurus-rex/images/preview-desktop-standard.webp': tyrannosaurusRexPreviewDesktopStandard.src,
  '../content/animals/tyrannosaurus-rex/images/preview-desktop-wide.webp': tyrannosaurusRexPreviewDesktopWide.src,
  '../content/animals/tyrannosaurus-rex/images/preview-landscape-compact.webp': tyrannosaurusRexPreviewLandscapeCompact.src,
  '../content/animals/tyrannosaurus-rex/images/preview-phone-compact.webp': tyrannosaurusRexPreviewPhoneCompact.src,
  '../content/animals/tyrannosaurus-rex/images/preview-phone-tall.webp': tyrannosaurusRexPreviewPhoneTall.src,
  '../content/animals/tyrannosaurus-rex/images/preview-tablet-portrait.webp': tyrannosaurusRexPreviewTabletPortrait.src,
}
