// Generated by npm run generate:registry. Do not edit by hand.
import type { AnimalModule } from './types'
import * as apatosaurus from './animals/apatosaurus/animal'
import * as arabianLeopard from './animals/arabian-leopard/animal'
import * as bear from './animals/bear/animal'
import * as bull from './animals/bull/animal'
import * as caneCorso from './animals/cane-corso/animal'
import * as centipede from './animals/centipede/animal'
import * as coyote from './animals/coyote/animal'
import * as crab from './animals/crab/animal'
import * as dilophosaurus from './animals/dilophosaurus/animal'
import * as duck from './animals/duck/animal'
import * as fennecFox from './animals/fennec-fox/animal'
import * as gigantoraptor from './animals/gigantoraptor/animal'
import * as ichthyosaur from './animals/ichthyosaur/animal'
import * as kitten from './animals/kitten/animal'
import * as maiasaura from './animals/maiasaura/animal'
import * as mammoth from './animals/mammoth/animal'
import * as megalodon from './animals/megalodon/animal'
import * as meganeura from './animals/meganeura/animal'
import * as mosasaurus from './animals/mosasaurus/animal'
import * as mouse from './animals/mouse/animal'
import * as norwegianForestCat from './animals/norwegian-forest-cat/animal'
import * as octopus from './animals/octopus/animal'
import * as owl from './animals/owl/animal'
import * as ox from './animals/ox/animal'
import * as pachycephalosaurus from './animals/pachycephalosaurus/animal'
import * as persianCat from './animals/persian-cat/animal'
import * as pigeon from './animals/pigeon/animal'
import * as pirateShepherdDog from './animals/pirate-shepherd-dog/animal'
import * as plesiosaurus from './animals/plesiosaurus/animal'
import * as pteranodon from './animals/pteranodon/animal'
import * as redPanda from './animals/red-panda/animal'
import * as rhamphorhynchus from './animals/rhamphorhynchus/animal'
import * as saberToothedTiger from './animals/saber-toothed-tiger/animal'
import * as salmon from './animals/salmon/animal'
import * as sauropelta from './animals/sauropelta/animal'
import * as shark from './animals/shark/animal'
import * as sheep from './animals/sheep/animal'
import * as sparrow from './animals/sparrow/animal'
import * as stagBeetle from './animals/stag-beetle/animal'
import * as stegosaurus from './animals/stegosaurus/animal'
import * as tiger from './animals/tiger/animal'
import * as tortoise from './animals/tortoise/animal'
import * as triceratops from './animals/triceratops/animal'
import * as tupandactylus from './animals/tupandactylus/animal'
import * as tyrannosaurusRex from './animals/tyrannosaurus-rex/animal'

export const animalModules: Readonly<Record<string, AnimalModule>> = {
  './animals/apatosaurus/animal.ts': apatosaurus,
  './animals/arabian-leopard/animal.ts': arabianLeopard,
  './animals/bear/animal.ts': bear,
  './animals/bull/animal.ts': bull,
  './animals/cane-corso/animal.ts': caneCorso,
  './animals/centipede/animal.ts': centipede,
  './animals/coyote/animal.ts': coyote,
  './animals/crab/animal.ts': crab,
  './animals/dilophosaurus/animal.ts': dilophosaurus,
  './animals/duck/animal.ts': duck,
  './animals/fennec-fox/animal.ts': fennecFox,
  './animals/gigantoraptor/animal.ts': gigantoraptor,
  './animals/ichthyosaur/animal.ts': ichthyosaur,
  './animals/kitten/animal.ts': kitten,
  './animals/maiasaura/animal.ts': maiasaura,
  './animals/mammoth/animal.ts': mammoth,
  './animals/megalodon/animal.ts': megalodon,
  './animals/meganeura/animal.ts': meganeura,
  './animals/mosasaurus/animal.ts': mosasaurus,
  './animals/mouse/animal.ts': mouse,
  './animals/norwegian-forest-cat/animal.ts': norwegianForestCat,
  './animals/octopus/animal.ts': octopus,
  './animals/owl/animal.ts': owl,
  './animals/ox/animal.ts': ox,
  './animals/pachycephalosaurus/animal.ts': pachycephalosaurus,
  './animals/persian-cat/animal.ts': persianCat,
  './animals/pigeon/animal.ts': pigeon,
  './animals/pirate-shepherd-dog/animal.ts': pirateShepherdDog,
  './animals/plesiosaurus/animal.ts': plesiosaurus,
  './animals/pteranodon/animal.ts': pteranodon,
  './animals/red-panda/animal.ts': redPanda,
  './animals/rhamphorhynchus/animal.ts': rhamphorhynchus,
  './animals/saber-toothed-tiger/animal.ts': saberToothedTiger,
  './animals/salmon/animal.ts': salmon,
  './animals/sauropelta/animal.ts': sauropelta,
  './animals/shark/animal.ts': shark,
  './animals/sheep/animal.ts': sheep,
  './animals/sparrow/animal.ts': sparrow,
  './animals/stag-beetle/animal.ts': stagBeetle,
  './animals/stegosaurus/animal.ts': stegosaurus,
  './animals/tiger/animal.ts': tiger,
  './animals/tortoise/animal.ts': tortoise,
  './animals/triceratops/animal.ts': triceratops,
  './animals/tupandactylus/animal.ts': tupandactylus,
  './animals/tyrannosaurus-rex/animal.ts': tyrannosaurusRex,
}
