// Generated by npm run generate:registry. Do not edit by hand.
import type { AnimalModule } from '@/src/content/types'
import * as africanLeopard from '@/src/content/animals/african-leopard/animal'
import * as akita from '@/src/content/animals/akita/animal'
import * as alexanderMassialasTouch from '@/src/content/animals/alexander-massialas-touch/animal'
import * as alligator from '@/src/content/animals/alligator/animal'
import * as alpaca from '@/src/content/animals/alpaca/animal'
import * as alpineGoat from '@/src/content/animals/alpine-goat/animal'
import * as anglerfish from '@/src/content/animals/anglerfish/animal'
import * as ankylosaurus from '@/src/content/animals/ankylosaurus/animal'
import * as apatosaurus from '@/src/content/animals/apatosaurus/animal'
import * as arabianHorse from '@/src/content/animals/arabian-horse/animal'
import * as arabianLeopard from '@/src/content/animals/arabian-leopard/animal'
import * as arcticFox from '@/src/content/animals/arctic-fox/animal'
import * as atlasBeetle from '@/src/content/animals/atlas-beetle/animal'
import * as atlasMoth from '@/src/content/animals/atlas-moth/animal'
import * as australianShepherd from '@/src/content/animals/australian-shepherd/animal'
import * as ballPython from '@/src/content/animals/ball-python/animal'
import * as beagle from '@/src/content/animals/beagle/animal'
import * as bear from '@/src/content/animals/bear/animal'
import * as bengalCat from '@/src/content/animals/bengal-cat/animal'
import * as borderCollie from '@/src/content/animals/border-collie/animal'
import * as brachiosaurus from '@/src/content/animals/brachiosaurus/animal'
import * as brownBear from '@/src/content/animals/brown-bear/animal'
import * as brownCicada from '@/src/content/animals/brown-cicada/animal'
import * as bull from '@/src/content/animals/bull/animal'
import * as bullTerrier from '@/src/content/animals/bull-terrier/animal'
import * as bulldog from '@/src/content/animals/bulldog/animal'
import * as bumblebee from '@/src/content/animals/bumblebee/animal'
import * as butterfly from '@/src/content/animals/butterfly/animal'
import * as caelebDresselButterfly from '@/src/content/animals/caeleb-dressel-butterfly/animal'
import * as caelebDresselFreestyle from '@/src/content/animals/caeleb-dressel-freestyle/animal'
import * as caelebDresselStart from '@/src/content/animals/caeleb-dressel-start/animal'
import * as caneCorso from '@/src/content/animals/cane-corso/animal'
import * as caneCorsoAr from '@/src/content/animals/cane-corso-ar/animal'
import * as centipede from '@/src/content/animals/centipede/animal'
import * as cheetah from '@/src/content/animals/cheetah/animal'
import * as chihuahua from '@/src/content/animals/chihuahua/animal'
import * as chipmunk from '@/src/content/animals/chipmunk/animal'
import * as chowChow from '@/src/content/animals/chow-chow/animal'
import * as cockerSpaniel from '@/src/content/animals/cocker-spaniel/animal'
import * as commonOctopus from '@/src/content/animals/common-octopus/animal'
import * as coyote from '@/src/content/animals/coyote/animal'
import * as crab from '@/src/content/animals/crab/animal'
import * as crow from '@/src/content/animals/crow/animal'
import * as dachshund from '@/src/content/animals/dachshund/animal'
import * as deer from '@/src/content/animals/deer/animal'
import * as dilophosaurus from '@/src/content/animals/dilophosaurus/animal'
import * as dilophosaurusAr from '@/src/content/animals/dilophosaurus-ar/animal'
import * as dinaAsherSmithSprint from '@/src/content/animals/dina-asher-smith-sprint/animal'
import * as dinaAsherSmithStart from '@/src/content/animals/dina-asher-smith-start/animal'
import * as dinaAsherSmithStride from '@/src/content/animals/dina-asher-smith-stride/animal'
import * as doberman from '@/src/content/animals/doberman/animal'
import * as donkey from '@/src/content/animals/donkey/animal'
import * as dragon from '@/src/content/animals/dragon/animal'
import * as dragonfly from '@/src/content/animals/dragonfly/animal'
import * as duck from '@/src/content/animals/duck/animal'
import * as eagle from '@/src/content/animals/eagle/animal'
import * as echidna from '@/src/content/animals/echidna/animal'
import * as elephant from '@/src/content/animals/elephant/animal'
import * as emperorPenguin from '@/src/content/animals/emperor-penguin/animal'
import * as emu from '@/src/content/animals/emu/animal'
import * as emuAr from '@/src/content/animals/emu-ar/animal'
import * as europeanHedgehog from '@/src/content/animals/european-hedgehog/animal'
import * as eveningCicada from '@/src/content/animals/evening-cicada/animal'
import * as fennecFox from '@/src/content/animals/fennec-fox/animal'
import * as firefly from '@/src/content/animals/firefly/animal'
import * as frenchBulldog from '@/src/content/animals/french-bulldog/animal'
import * as frog from '@/src/content/animals/frog/animal'
import * as germanShepherd from '@/src/content/animals/german-shepherd/animal'
import * as giantPanda from '@/src/content/animals/giant-panda/animal'
import * as giantStagBeetle from '@/src/content/animals/giant-stag-beetle/animal'
import * as gigantoraptor from '@/src/content/animals/gigantoraptor/animal'
import * as giraffe from '@/src/content/animals/giraffe/animal'
import * as goat from '@/src/content/animals/goat/animal'
import * as goldenEagle from '@/src/content/animals/golden-eagle/animal'
import * as goldenRetriever from '@/src/content/animals/golden-retriever/animal'
import * as grasshopper from '@/src/content/animals/grasshopper/animal'
import * as greatDane from '@/src/content/animals/great-dane/animal'
import * as greatWhiteShark from '@/src/content/animals/great-white-shark/animal'
import * as greenSeaTurtle from '@/src/content/animals/green-sea-turtle/animal'
import * as grogu from '@/src/content/animals/grogu/animal'
import * as guineaPig from '@/src/content/animals/guinea-pig/animal'
import * as hamster from '@/src/content/animals/hamster/animal'
import * as herculesBeetle from '@/src/content/animals/hercules-beetle/animal'
import * as herculesBeetleAr from '@/src/content/animals/hercules-beetle-ar/animal'
import * as hippo from '@/src/content/animals/hippo/animal'
import * as hornet from '@/src/content/animals/hornet/animal'
import * as horse from '@/src/content/animals/horse/animal'
import * as ichthyosaur from '@/src/content/animals/ichthyosaur/animal'
import * as jellyfish from '@/src/content/animals/jellyfish/animal'
import * as jewelBeetle from '@/src/content/animals/jewel-beetle/animal'
import * as jindoDog from '@/src/content/animals/jindo-dog/animal'
import * as kangaroo from '@/src/content/animals/kangaroo/animal'
import * as kangarooAr from '@/src/content/animals/kangaroo-ar/animal'
import * as kitten from '@/src/content/animals/kitten/animal'
import * as koala from '@/src/content/animals/koala/animal'
import * as kookaburra from '@/src/content/animals/kookaburra/animal'
import * as kookaburraAr from '@/src/content/animals/kookaburra-ar/animal'
import * as labradorRetriever from '@/src/content/animals/labrador-retriever/animal'
import * as labradorRetriever2 from '@/src/content/animals/labrador-retriever-2/animal'
import * as ladybug from '@/src/content/animals/ladybug/animal'
import * as lion from '@/src/content/animals/lion/animal'
import * as lionAr from '@/src/content/animals/lion-ar/animal'
import * as lynx from '@/src/content/animals/lynx/animal'
import * as macaw from '@/src/content/animals/macaw/animal'
import * as maiasaura from '@/src/content/animals/maiasaura/animal'
import * as maineCoon from '@/src/content/animals/maine-coon/animal'
import * as mallardDuck from '@/src/content/animals/mallard-duck/animal'
import * as maltese from '@/src/content/animals/maltese/animal'
import * as mammoth from '@/src/content/animals/mammoth/animal'
import * as mantis from '@/src/content/animals/mantis/animal'
import * as megalodon from '@/src/content/animals/megalodon/animal'
import * as meganRapinoeDribble from '@/src/content/animals/megan-rapinoe-dribble/animal'
import * as meganeura from '@/src/content/animals/meganeura/animal'
import * as meiPanda from '@/src/content/animals/mei-panda/animal'
import * as milkCow from '@/src/content/animals/milk-cow/animal'
import * as morphoButterfly from '@/src/content/animals/morpho-butterfly/animal'
import * as mosasaurus from '@/src/content/animals/mosasaurus/animal'
import * as mouse from '@/src/content/animals/mouse/animal'
import * as niklasKaulLongjump from '@/src/content/animals/niklas-kaul-longjump/animal'
import * as norwegianForestCat from '@/src/content/animals/norwegian-forest-cat/animal'
import * as octopus from '@/src/content/animals/octopus/animal'
import * as owl from '@/src/content/animals/owl/animal'
import * as ox from '@/src/content/animals/ox/animal'
import * as oxAr from '@/src/content/animals/ox-ar/animal'
import * as pachycephalosaurus from '@/src/content/animals/pachycephalosaurus/animal'
import * as parasaurolophus from '@/src/content/animals/parasaurolophus/animal'
import * as periodicalCicada from '@/src/content/animals/periodical-cicada/animal'
import * as persianCat from '@/src/content/animals/persian-cat/animal'
import * as pig from '@/src/content/animals/pig/animal'
import * as pigeon from '@/src/content/animals/pigeon/animal'
import * as pirateShepherdDog from '@/src/content/animals/pirate-shepherd-dog/animal'
import * as pitbull from '@/src/content/animals/pitbull/animal'
import * as platypus from '@/src/content/animals/platypus/animal'
import * as plesiosaurus from '@/src/content/animals/plesiosaurus/animal'
import * as pomeranian from '@/src/content/animals/pomeranian/animal'
import * as pony from '@/src/content/animals/pony/animal'
import * as poodle from '@/src/content/animals/poodle/animal'
import * as porpoise from '@/src/content/animals/porpoise/animal'
import * as pteranodon from '@/src/content/animals/pteranodon/animal'
import * as pteranodonAr from '@/src/content/animals/pteranodon-ar/animal'
import * as pug from '@/src/content/animals/pug/animal'
import * as pugAr from '@/src/content/animals/pug-ar/animal'
import * as pvSindhuRally from '@/src/content/animals/pv-sindhu-rally/animal'
import * as pvSindhuShots from '@/src/content/animals/pv-sindhu-shots/animal'
import * as pvSindhuSmash from '@/src/content/animals/pv-sindhu-smash/animal'
import * as python from '@/src/content/animals/python/animal'
import * as quokka from '@/src/content/animals/quokka/animal'
import * as rabbit from '@/src/content/animals/rabbit/animal'
import * as rabbitAr from '@/src/content/animals/rabbit-ar/animal'
import * as raccoon from '@/src/content/animals/raccoon/animal'
import * as raccoonAr from '@/src/content/animals/raccoon-ar/animal'
import * as ragdoll from '@/src/content/animals/ragdoll/animal'
import * as redPanda from '@/src/content/animals/red-panda/animal'
import * as rhamphorhynchus from '@/src/content/animals/rhamphorhynchus/animal'
import * as rhinocerosBeetle from '@/src/content/animals/rhinoceros-beetle/animal'
import * as robustCicada from '@/src/content/animals/robust-cicada/animal'
import * as rosaliaBatesi from '@/src/content/animals/rosalia-batesi/animal'
import * as rottweiler from '@/src/content/animals/rottweiler/animal'
import * as russianBlue from '@/src/content/animals/russian-blue/animal'
import * as saberToothedTiger from '@/src/content/animals/saber-toothed-tiger/animal'
import * as salmon from '@/src/content/animals/salmon/animal'
import * as santaClaus from '@/src/content/animals/santa-claus/animal'
import * as saola from '@/src/content/animals/saola/animal'
import * as sauropelta from '@/src/content/animals/sauropelta/animal'
import * as schnauzer from '@/src/content/animals/schnauzer/animal'
import * as schnauzerAr from '@/src/content/animals/schnauzer-ar/animal'
import * as scorpion from '@/src/content/animals/scorpion/animal'
import * as scottishFold from '@/src/content/animals/scottish-fold/animal'
import * as seaTurtle from '@/src/content/animals/sea-turtle/animal'
import * as seahorse from '@/src/content/animals/seahorse/animal'
import * as shark from '@/src/content/animals/shark/animal'
import * as sheep from '@/src/content/animals/sheep/animal'
import * as shibaInu from '@/src/content/animals/shiba-inu/animal'
import * as shihTzu from '@/src/content/animals/shih-tzu/animal'
import * as shiningBallScarab from '@/src/content/animals/shining-ball-scarab/animal'
import * as shortHairedCat from '@/src/content/animals/short-haired-cat/animal'
import * as siamese from '@/src/content/animals/siamese/animal'
import * as siberianHusky from '@/src/content/animals/siberian-husky/animal'
import * as snail from '@/src/content/animals/snail/animal'
import * as sparrow from '@/src/content/animals/sparrow/animal'
import * as sphynxCat from '@/src/content/animals/sphynx-cat/animal'
import * as sphynxCatAr from '@/src/content/animals/sphynx-cat-ar/animal'
import * as spinosaurus from '@/src/content/animals/spinosaurus/animal'
import * as stagBeetle from '@/src/content/animals/stag-beetle/animal'
import * as stagBeetle2 from '@/src/content/animals/stag-beetle-2/animal'
import * as stegosaurus from '@/src/content/animals/stegosaurus/animal'
import * as stegosaurusAr from '@/src/content/animals/stegosaurus-ar/animal'
import * as swallowtailButterfly from '@/src/content/animals/swallowtail-butterfly/animal'
import * as tiger from '@/src/content/animals/tiger/animal'
import * as tigerAr from '@/src/content/animals/tiger-ar/animal'
import * as timberWolf from '@/src/content/animals/timber-wolf/animal'
import * as tortoise from '@/src/content/animals/tortoise/animal'
import * as triceratops from '@/src/content/animals/triceratops/animal'
import * as triceratopsAr from '@/src/content/animals/triceratops-ar/animal'
import * as tupandactylus from '@/src/content/animals/tupandactylus/animal'
import * as tyrannosaurusRex from '@/src/content/animals/tyrannosaurus-rex/animal'
import * as tyrannosaurusRexAr from '@/src/content/animals/tyrannosaurus-rex-ar/animal'
import * as unicorn from '@/src/content/animals/unicorn/animal'
import * as velociraptor from '@/src/content/animals/velociraptor/animal'
import * as walkersCicada from '@/src/content/animals/walkers-cicada/animal'
import * as welshCorgi from '@/src/content/animals/welsh-corgi/animal'
import * as whale from '@/src/content/animals/whale/animal'
import * as whiteTailedDeer from '@/src/content/animals/white-tailed-deer/animal'
import * as wombat from '@/src/content/animals/wombat/animal'
import * as woodpecker from '@/src/content/animals/woodpecker/animal'
import * as yorkshireTerrier from '@/src/content/animals/yorkshire-terrier/animal'
import * as zebra from '@/src/content/animals/zebra/animal'
import * as zebraAr from '@/src/content/animals/zebra-ar/animal'

export const animalModules: Readonly<Record<string, AnimalModule>> = {
  './animals/african-leopard/animal.ts': africanLeopard,
  './animals/akita/animal.ts': akita,
  './animals/alexander-massialas-touch/animal.ts': alexanderMassialasTouch,
  './animals/alligator/animal.ts': alligator,
  './animals/alpaca/animal.ts': alpaca,
  './animals/alpine-goat/animal.ts': alpineGoat,
  './animals/anglerfish/animal.ts': anglerfish,
  './animals/ankylosaurus/animal.ts': ankylosaurus,
  './animals/apatosaurus/animal.ts': apatosaurus,
  './animals/arabian-horse/animal.ts': arabianHorse,
  './animals/arabian-leopard/animal.ts': arabianLeopard,
  './animals/arctic-fox/animal.ts': arcticFox,
  './animals/atlas-beetle/animal.ts': atlasBeetle,
  './animals/atlas-moth/animal.ts': atlasMoth,
  './animals/australian-shepherd/animal.ts': australianShepherd,
  './animals/ball-python/animal.ts': ballPython,
  './animals/beagle/animal.ts': beagle,
  './animals/bear/animal.ts': bear,
  './animals/bengal-cat/animal.ts': bengalCat,
  './animals/border-collie/animal.ts': borderCollie,
  './animals/brachiosaurus/animal.ts': brachiosaurus,
  './animals/brown-bear/animal.ts': brownBear,
  './animals/brown-cicada/animal.ts': brownCicada,
  './animals/bull/animal.ts': bull,
  './animals/bull-terrier/animal.ts': bullTerrier,
  './animals/bulldog/animal.ts': bulldog,
  './animals/bumblebee/animal.ts': bumblebee,
  './animals/butterfly/animal.ts': butterfly,
  './animals/caeleb-dressel-butterfly/animal.ts': caelebDresselButterfly,
  './animals/caeleb-dressel-freestyle/animal.ts': caelebDresselFreestyle,
  './animals/caeleb-dressel-start/animal.ts': caelebDresselStart,
  './animals/cane-corso/animal.ts': caneCorso,
  './animals/cane-corso-ar/animal.ts': caneCorsoAr,
  './animals/centipede/animal.ts': centipede,
  './animals/cheetah/animal.ts': cheetah,
  './animals/chihuahua/animal.ts': chihuahua,
  './animals/chipmunk/animal.ts': chipmunk,
  './animals/chow-chow/animal.ts': chowChow,
  './animals/cocker-spaniel/animal.ts': cockerSpaniel,
  './animals/common-octopus/animal.ts': commonOctopus,
  './animals/coyote/animal.ts': coyote,
  './animals/crab/animal.ts': crab,
  './animals/crow/animal.ts': crow,
  './animals/dachshund/animal.ts': dachshund,
  './animals/deer/animal.ts': deer,
  './animals/dilophosaurus/animal.ts': dilophosaurus,
  './animals/dilophosaurus-ar/animal.ts': dilophosaurusAr,
  './animals/dina-asher-smith-sprint/animal.ts': dinaAsherSmithSprint,
  './animals/dina-asher-smith-start/animal.ts': dinaAsherSmithStart,
  './animals/dina-asher-smith-stride/animal.ts': dinaAsherSmithStride,
  './animals/doberman/animal.ts': doberman,
  './animals/donkey/animal.ts': donkey,
  './animals/dragon/animal.ts': dragon,
  './animals/dragonfly/animal.ts': dragonfly,
  './animals/duck/animal.ts': duck,
  './animals/eagle/animal.ts': eagle,
  './animals/echidna/animal.ts': echidna,
  './animals/elephant/animal.ts': elephant,
  './animals/emperor-penguin/animal.ts': emperorPenguin,
  './animals/emu/animal.ts': emu,
  './animals/emu-ar/animal.ts': emuAr,
  './animals/european-hedgehog/animal.ts': europeanHedgehog,
  './animals/evening-cicada/animal.ts': eveningCicada,
  './animals/fennec-fox/animal.ts': fennecFox,
  './animals/firefly/animal.ts': firefly,
  './animals/french-bulldog/animal.ts': frenchBulldog,
  './animals/frog/animal.ts': frog,
  './animals/german-shepherd/animal.ts': germanShepherd,
  './animals/giant-panda/animal.ts': giantPanda,
  './animals/giant-stag-beetle/animal.ts': giantStagBeetle,
  './animals/gigantoraptor/animal.ts': gigantoraptor,
  './animals/giraffe/animal.ts': giraffe,
  './animals/goat/animal.ts': goat,
  './animals/golden-eagle/animal.ts': goldenEagle,
  './animals/golden-retriever/animal.ts': goldenRetriever,
  './animals/grasshopper/animal.ts': grasshopper,
  './animals/great-dane/animal.ts': greatDane,
  './animals/great-white-shark/animal.ts': greatWhiteShark,
  './animals/green-sea-turtle/animal.ts': greenSeaTurtle,
  './animals/grogu/animal.ts': grogu,
  './animals/guinea-pig/animal.ts': guineaPig,
  './animals/hamster/animal.ts': hamster,
  './animals/hercules-beetle/animal.ts': herculesBeetle,
  './animals/hercules-beetle-ar/animal.ts': herculesBeetleAr,
  './animals/hippo/animal.ts': hippo,
  './animals/hornet/animal.ts': hornet,
  './animals/horse/animal.ts': horse,
  './animals/ichthyosaur/animal.ts': ichthyosaur,
  './animals/jellyfish/animal.ts': jellyfish,
  './animals/jewel-beetle/animal.ts': jewelBeetle,
  './animals/jindo-dog/animal.ts': jindoDog,
  './animals/kangaroo/animal.ts': kangaroo,
  './animals/kangaroo-ar/animal.ts': kangarooAr,
  './animals/kitten/animal.ts': kitten,
  './animals/koala/animal.ts': koala,
  './animals/kookaburra/animal.ts': kookaburra,
  './animals/kookaburra-ar/animal.ts': kookaburraAr,
  './animals/labrador-retriever/animal.ts': labradorRetriever,
  './animals/labrador-retriever-2/animal.ts': labradorRetriever2,
  './animals/ladybug/animal.ts': ladybug,
  './animals/lion/animal.ts': lion,
  './animals/lion-ar/animal.ts': lionAr,
  './animals/lynx/animal.ts': lynx,
  './animals/macaw/animal.ts': macaw,
  './animals/maiasaura/animal.ts': maiasaura,
  './animals/maine-coon/animal.ts': maineCoon,
  './animals/mallard-duck/animal.ts': mallardDuck,
  './animals/maltese/animal.ts': maltese,
  './animals/mammoth/animal.ts': mammoth,
  './animals/mantis/animal.ts': mantis,
  './animals/megalodon/animal.ts': megalodon,
  './animals/megan-rapinoe-dribble/animal.ts': meganRapinoeDribble,
  './animals/meganeura/animal.ts': meganeura,
  './animals/mei-panda/animal.ts': meiPanda,
  './animals/milk-cow/animal.ts': milkCow,
  './animals/morpho-butterfly/animal.ts': morphoButterfly,
  './animals/mosasaurus/animal.ts': mosasaurus,
  './animals/mouse/animal.ts': mouse,
  './animals/niklas-kaul-longjump/animal.ts': niklasKaulLongjump,
  './animals/norwegian-forest-cat/animal.ts': norwegianForestCat,
  './animals/octopus/animal.ts': octopus,
  './animals/owl/animal.ts': owl,
  './animals/ox/animal.ts': ox,
  './animals/ox-ar/animal.ts': oxAr,
  './animals/pachycephalosaurus/animal.ts': pachycephalosaurus,
  './animals/parasaurolophus/animal.ts': parasaurolophus,
  './animals/periodical-cicada/animal.ts': periodicalCicada,
  './animals/persian-cat/animal.ts': persianCat,
  './animals/pig/animal.ts': pig,
  './animals/pigeon/animal.ts': pigeon,
  './animals/pirate-shepherd-dog/animal.ts': pirateShepherdDog,
  './animals/pitbull/animal.ts': pitbull,
  './animals/platypus/animal.ts': platypus,
  './animals/plesiosaurus/animal.ts': plesiosaurus,
  './animals/pomeranian/animal.ts': pomeranian,
  './animals/pony/animal.ts': pony,
  './animals/poodle/animal.ts': poodle,
  './animals/porpoise/animal.ts': porpoise,
  './animals/pteranodon/animal.ts': pteranodon,
  './animals/pteranodon-ar/animal.ts': pteranodonAr,
  './animals/pug/animal.ts': pug,
  './animals/pug-ar/animal.ts': pugAr,
  './animals/pv-sindhu-rally/animal.ts': pvSindhuRally,
  './animals/pv-sindhu-shots/animal.ts': pvSindhuShots,
  './animals/pv-sindhu-smash/animal.ts': pvSindhuSmash,
  './animals/python/animal.ts': python,
  './animals/quokka/animal.ts': quokka,
  './animals/rabbit/animal.ts': rabbit,
  './animals/rabbit-ar/animal.ts': rabbitAr,
  './animals/raccoon/animal.ts': raccoon,
  './animals/raccoon-ar/animal.ts': raccoonAr,
  './animals/ragdoll/animal.ts': ragdoll,
  './animals/red-panda/animal.ts': redPanda,
  './animals/rhamphorhynchus/animal.ts': rhamphorhynchus,
  './animals/rhinoceros-beetle/animal.ts': rhinocerosBeetle,
  './animals/robust-cicada/animal.ts': robustCicada,
  './animals/rosalia-batesi/animal.ts': rosaliaBatesi,
  './animals/rottweiler/animal.ts': rottweiler,
  './animals/russian-blue/animal.ts': russianBlue,
  './animals/saber-toothed-tiger/animal.ts': saberToothedTiger,
  './animals/salmon/animal.ts': salmon,
  './animals/santa-claus/animal.ts': santaClaus,
  './animals/saola/animal.ts': saola,
  './animals/sauropelta/animal.ts': sauropelta,
  './animals/schnauzer/animal.ts': schnauzer,
  './animals/schnauzer-ar/animal.ts': schnauzerAr,
  './animals/scorpion/animal.ts': scorpion,
  './animals/scottish-fold/animal.ts': scottishFold,
  './animals/sea-turtle/animal.ts': seaTurtle,
  './animals/seahorse/animal.ts': seahorse,
  './animals/shark/animal.ts': shark,
  './animals/sheep/animal.ts': sheep,
  './animals/shiba-inu/animal.ts': shibaInu,
  './animals/shih-tzu/animal.ts': shihTzu,
  './animals/shining-ball-scarab/animal.ts': shiningBallScarab,
  './animals/short-haired-cat/animal.ts': shortHairedCat,
  './animals/siamese/animal.ts': siamese,
  './animals/siberian-husky/animal.ts': siberianHusky,
  './animals/snail/animal.ts': snail,
  './animals/sparrow/animal.ts': sparrow,
  './animals/sphynx-cat/animal.ts': sphynxCat,
  './animals/sphynx-cat-ar/animal.ts': sphynxCatAr,
  './animals/spinosaurus/animal.ts': spinosaurus,
  './animals/stag-beetle/animal.ts': stagBeetle,
  './animals/stag-beetle-2/animal.ts': stagBeetle2,
  './animals/stegosaurus/animal.ts': stegosaurus,
  './animals/stegosaurus-ar/animal.ts': stegosaurusAr,
  './animals/swallowtail-butterfly/animal.ts': swallowtailButterfly,
  './animals/tiger/animal.ts': tiger,
  './animals/tiger-ar/animal.ts': tigerAr,
  './animals/timber-wolf/animal.ts': timberWolf,
  './animals/tortoise/animal.ts': tortoise,
  './animals/triceratops/animal.ts': triceratops,
  './animals/triceratops-ar/animal.ts': triceratopsAr,
  './animals/tupandactylus/animal.ts': tupandactylus,
  './animals/tyrannosaurus-rex/animal.ts': tyrannosaurusRex,
  './animals/tyrannosaurus-rex-ar/animal.ts': tyrannosaurusRexAr,
  './animals/unicorn/animal.ts': unicorn,
  './animals/velociraptor/animal.ts': velociraptor,
  './animals/walkers-cicada/animal.ts': walkersCicada,
  './animals/welsh-corgi/animal.ts': welshCorgi,
  './animals/whale/animal.ts': whale,
  './animals/white-tailed-deer/animal.ts': whiteTailedDeer,
  './animals/wombat/animal.ts': wombat,
  './animals/woodpecker/animal.ts': woodpecker,
  './animals/yorkshire-terrier/animal.ts': yorkshireTerrier,
  './animals/zebra/animal.ts': zebra,
  './animals/zebra-ar/animal.ts': zebraAr,
}
