// Generated by npm run generate:registry. Do not edit by hand.
import type { AnimalModule } from './types'
import * as apatosaurus from './animals/apatosaurus/animal'
import * as dilophosaurus from './animals/dilophosaurus/animal'
import * as gigantoraptor from './animals/gigantoraptor/animal'
import * as ichthyosaur from './animals/ichthyosaur/animal'
import * as maiasaura from './animals/maiasaura/animal'
import * as mammoth from './animals/mammoth/animal'
import * as megalodon from './animals/megalodon/animal'
import * as meganeura from './animals/meganeura/animal'
import * as mosasaurus from './animals/mosasaurus/animal'
import * as pachycephalosaurus from './animals/pachycephalosaurus/animal'
import * as plesiosaurus from './animals/plesiosaurus/animal'
import * as pteranodon from './animals/pteranodon/animal'
import * as rhamphorhynchus from './animals/rhamphorhynchus/animal'
import * as sauropelta from './animals/sauropelta/animal'
import * as stegosaurus from './animals/stegosaurus/animal'
import * as tiger from './animals/tiger/animal'
import * as triceratops from './animals/triceratops/animal'
import * as tupandactylus from './animals/tupandactylus/animal'
import * as tyrannosaurusRex from './animals/tyrannosaurus-rex/animal'

export const animalModules: Readonly<Record<string, AnimalModule>> = {
  './animals/apatosaurus/animal.ts': apatosaurus,
  './animals/dilophosaurus/animal.ts': dilophosaurus,
  './animals/gigantoraptor/animal.ts': gigantoraptor,
  './animals/ichthyosaur/animal.ts': ichthyosaur,
  './animals/maiasaura/animal.ts': maiasaura,
  './animals/mammoth/animal.ts': mammoth,
  './animals/megalodon/animal.ts': megalodon,
  './animals/meganeura/animal.ts': meganeura,
  './animals/mosasaurus/animal.ts': mosasaurus,
  './animals/pachycephalosaurus/animal.ts': pachycephalosaurus,
  './animals/plesiosaurus/animal.ts': plesiosaurus,
  './animals/pteranodon/animal.ts': pteranodon,
  './animals/rhamphorhynchus/animal.ts': rhamphorhynchus,
  './animals/sauropelta/animal.ts': sauropelta,
  './animals/stegosaurus/animal.ts': stegosaurus,
  './animals/tiger/animal.ts': tiger,
  './animals/triceratops/animal.ts': triceratops,
  './animals/tupandactylus/animal.ts': tupandactylus,
  './animals/tyrannosaurus-rex/animal.ts': tyrannosaurusRex,
}
