import { readdir } from 'node:fs/promises'
import { join } from 'node:path'

import { animalsRoot } from './content-data'

// Renders the checked-in module registries that replaced Vite's
// `import.meta.glob` discovery. Keeping the registries as generated source
// files preserves the zero-touch onboarding flow: adding an animal directory
// and running `npm run generate:registry` (or failing `validate:content`)
// keeps them current.

function toIdentifier(parts: readonly string[]): string {
  return parts
    .map((part, index) => {
      if (index === 0) {
        return part
      }
      const [first, ...rest] = part
      return `${(first ?? '').toUpperCase()}${rest.join('')}`
    })
    .join('')
}

async function animalDirectoryNames(): Promise<string[]> {
  const entries = await readdir(animalsRoot, { withFileTypes: true })
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
}

async function previewFileNames(directoryName: string): Promise<string[]> {
  const imageRoot = join(animalsRoot, directoryName, 'images')
  const entries = await readdir(imageRoot)
  return entries
    .filter((name) => /^preview-.*\.webp$/.test(name))
    .sort()
}

export async function renderAnimalModulesModule(): Promise<string> {
  const directoryNames = await animalDirectoryNames()
  const imports = directoryNames.map(
    (name) =>
      `import * as ${toIdentifier(name.split('-'))} from './animals/${name}/animal'`,
  )
  const entries = directoryNames.map(
    (name) =>
      `  './animals/${name}/animal.ts': ${toIdentifier(name.split('-'))},`,
  )
  return `// Generated by npm run generate:registry. Do not edit by hand.
import type { AnimalModule } from './types'
${imports.join('\n')}

export const animalModules: Readonly<Record<string, AnimalModule>> = {
${entries.join('\n')}
}
`
}

export async function renderModelPreviewModulesModule(): Promise<string> {
  const directoryNames = await animalDirectoryNames()
  const imports: string[] = []
  const entries: string[] = []
  for (const directoryName of directoryNames) {
    const fileNames = await previewFileNames(directoryName)
    for (const fileName of fileNames) {
      const identifier = toIdentifier([
        ...directoryName.split('-'),
        ...fileName.replace(/\.webp$/, '').split('-'),
      ])
      imports.push(
        `import ${identifier} from '../content/animals/${directoryName}/images/${fileName}'`,
      )
      entries.push(
        `  '../content/animals/${directoryName}/images/${fileName}': ${identifier}.src,`,
      )
    }
  }
  return `// Generated by npm run generate:registry. Do not edit by hand.
${imports.join('\n')}

export const modelPreviewModules: Readonly<Record<string, string>> = {
${entries.join('\n')}
}
`
}
