import { mkdir, rm, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

// The local review asset route only exists while a review dev server runs.
// It is installed right before `next dev` starts and removed again on
// shutdown, so private review material can never be compiled into a
// production build.
//
// The folder name URL-encodes the leading underscores: Next treats segments
// starting with `_` as private and would exclude the route otherwise.

export const repositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
)

const reviewRouteDirectory = resolve(
  repositoryRoot,
  'app/%5F%5Fmuseum-review-assets/[...reviewAssetPath]',
)

const reviewRouteSource = `// Generated by scripts/review-dev-route.ts for local review dev runs only.
// This route is removed again when the review server stops; never commit it.
import { handleLocalReviewAssetRequest } from '../../../scripts/review-assets'

export const dynamic = 'force-dynamic'

type ReviewAssetRouteContext = {
  params: Promise<{ reviewAssetPath: string[] }>
}

export async function GET(
  request: Request,
  context: ReviewAssetRouteContext,
): Promise<Response> {
  const { reviewAssetPath } = await context.params
  return handleLocalReviewAssetRequest(reviewAssetPath, request)
}

export async function HEAD(
  request: Request,
  context: ReviewAssetRouteContext,
): Promise<Response> {
  const { reviewAssetPath } = await context.params
  return handleLocalReviewAssetRequest(reviewAssetPath, request)
}
`

export async function installLocalReviewAssetRoute(): Promise<void> {
  await mkdir(reviewRouteDirectory, { recursive: true })
  await writeFile(
    resolve(reviewRouteDirectory, 'route.ts'),
    reviewRouteSource,
    'utf8',
  )
}

export async function removeLocalReviewAssetRoute(): Promise<void> {
  await rm(resolve(repositoryRoot, 'app/%5F%5Fmuseum-review-assets'), {
    force: true,
    recursive: true,
  })
}
